{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcwaas",
    "version": "0.1.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.ahnlab",
          "module": "abcmpc",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcwaas-0.1.25.aar",
          "url": "abcwaas-0.1.25.aar",
          "size": 9515445,
          "sha512": "8ead4bd6554d25a1feb8dc6825c39c42d04ade519133db1d455eab722ebacdb0450bb758c357174874f1b4f3000989e0035ee67f4cc2bf974fbe9c36eae6376d",
          "sha256": "054ca69fa2fbeb32842107cd452c774b9f50e51e5b428b52f3c9a11678214798",
          "sha1": "26e3efebac9178b76a8a73d1667d4ce641045ee6",
          "md5": "143529ed19b11d5a7923f3ebaa89cf07"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ahnlab",
          "module": "abcmpc",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcwaas-0.1.25.aar",
          "url": "abcwaas-0.1.25.aar",
          "size": 9515445,
          "sha512": "8ead4bd6554d25a1feb8dc6825c39c42d04ade519133db1d455eab722ebacdb0450bb758c357174874f1b4f3000989e0035ee67f4cc2bf974fbe9c36eae6376d",
          "sha256": "054ca69fa2fbeb32842107cd452c774b9f50e51e5b428b52f3c9a11678214798",
          "sha1": "26e3efebac9178b76a8a73d1667d4ce641045ee6",
          "md5": "143529ed19b11d5a7923f3ebaa89cf07"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "abcwaas-0.1.25-sources.jar",
          "url": "abcwaas-0.1.25-sources.jar",
          "size": 9150,
          "sha512": "8ac3384a9f416647edc006c77ffd903e7ba8682bcc09b3de87687809b92018052b5263bb28ff4ffb0e55ce9a4186718f3ab881d2cf4f5026cb415c6b84f5f6fa",
          "sha256": "fdbabe120e23e1d9e90126263ea1ab7066c2428aa371e93ac77711908fcd89db",
          "sha1": "c7ac0c214f5377487224515507a5f3eff4d5196d",
          "md5": "c9560e62ac27436249d4eebd9a0a8dcb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "abcwaas-0.1.25-javadoc.jar",
          "url": "abcwaas-0.1.25-javadoc.jar",
          "size": 393509,
          "sha512": "0ef8de737239edd27066a78a48189d94377f1a784fda457bb5b22db4d278cb8333ea55e63459bbf59e384e9fd50edc59687d5599aa92e64f9bee6b12c9f40464",
          "sha256": "aaed4ef205ee90a9cd2f920af4b9bce68cb825ca9bb14d8caba28eaf8c69c6d6",
          "sha1": "14db4884a235e6620b606279ab65ab1a39e8358e",
          "md5": "57cbdfb277953047ca63fbc1d3c5b122"
        }
      ]
    }
  ]
}
