{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcwaas",
    "version": "0.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.ahnlab",
          "module": "abcmpc",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcwaas-0.1.21.aar",
          "url": "abcwaas-0.1.21.aar",
          "size": 9508269,
          "sha512": "28cb4f785b56d2d47ef06e27c78755242e52cd55fdce472b551273ac612f0b75088cc626354313e1437d87734e03a9ebc70702b5ac3420e5b6bbf05118e6e3fb",
          "sha256": "758109a8292961de8a52f92a769160a5c191566ec5cdc1d0d7764339a71f7ca3",
          "sha1": "4c096be10dbd4db1ee6f71a8e6ec237e2fd53da8",
          "md5": "3f7daba68963fc5420b828e36eaeee98"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ahnlab",
          "module": "abcmpc",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcwaas-0.1.21.aar",
          "url": "abcwaas-0.1.21.aar",
          "size": 9508269,
          "sha512": "28cb4f785b56d2d47ef06e27c78755242e52cd55fdce472b551273ac612f0b75088cc626354313e1437d87734e03a9ebc70702b5ac3420e5b6bbf05118e6e3fb",
          "sha256": "758109a8292961de8a52f92a769160a5c191566ec5cdc1d0d7764339a71f7ca3",
          "sha1": "4c096be10dbd4db1ee6f71a8e6ec237e2fd53da8",
          "md5": "3f7daba68963fc5420b828e36eaeee98"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "abcwaas-0.1.21-sources.jar",
          "url": "abcwaas-0.1.21-sources.jar",
          "size": 7193,
          "sha512": "dab3d32bd49678c3a0b7275bd6ca94c56e9847c2a43b5db1b1297cb16ae7a7d454ee9588c50f9b17b391eb146398ff460f2287ffb8127503ed4e4bce408f67d7",
          "sha256": "0e2e693d7cc687fcf12ffc70b1c9676046ba73f8f8e7b583ffbf2b042de98113",
          "sha1": "278cf427c865b4391d401e301b730147f75cfc83",
          "md5": "7a403c118c411de9abb177889198dc9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "abcwaas-0.1.21-javadoc.jar",
          "url": "abcwaas-0.1.21-javadoc.jar",
          "size": 380166,
          "sha512": "2361e3349bcef2e9810b0a90fbec888420a646d2c7cb41b4a67a2e5e5f6a7b9d7038c85e0fdc54c693d8027fa23ac296eba76bcb843815578268fe9165460d80",
          "sha256": "59ad9ab8caf12f0dfbf8a1216fba06b87ca44c1d0b9777dc0809bf4a3e5fc986",
          "sha1": "62cde03cfd75b8060586ecc5f001d1fd277e3a49",
          "md5": "bac96c01cb16564b461138114107efe0"
        }
      ]
    }
  ]
}
