{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcwaas",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.ahnlab",
          "module": "abcmpc",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcwaas-0.1.7.aar",
          "url": "abcwaas-0.1.7.aar",
          "size": 9113349,
          "sha512": "214e231a98bf09429013e44729ef686bc9d71c190d0b83c559bff1b8b80806a77f7b690f66db5d485ff0e8ca786a1305c13575e6efc8069ca0248e301fd60515",
          "sha256": "4f3e172bfdfee29db1ce481f868aa9ae170578e5fe5bd5ed3e6992db0fbf3702",
          "sha1": "9c63356cdfe11730d52dbe1fb5597384c8404a57",
          "md5": "4d22c7c478e3e70a5fa91f19300e305e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ahnlab",
          "module": "abcmpc",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcwaas-0.1.7.aar",
          "url": "abcwaas-0.1.7.aar",
          "size": 9113349,
          "sha512": "214e231a98bf09429013e44729ef686bc9d71c190d0b83c559bff1b8b80806a77f7b690f66db5d485ff0e8ca786a1305c13575e6efc8069ca0248e301fd60515",
          "sha256": "4f3e172bfdfee29db1ce481f868aa9ae170578e5fe5bd5ed3e6992db0fbf3702",
          "sha1": "9c63356cdfe11730d52dbe1fb5597384c8404a57",
          "md5": "4d22c7c478e3e70a5fa91f19300e305e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "abcwaas-0.1.7-sources.jar",
          "url": "abcwaas-0.1.7-sources.jar",
          "size": 7454,
          "sha512": "f6ad0d8ea10f76b85903a2ed18c1fc141879e732b9d45055c3c21140eaf3f84b06b7e83801cde89023f40ae14a4be9692d90e6ba5b170c3eae922a5f8c56bdad",
          "sha256": "5307b2e99b4345397402ff46d17d54a73ffc94df38c4aa4cbcc8e10d5a24cd0b",
          "sha1": "629c92c934d180a707cc33b44044d56d7026a22f",
          "md5": "2637f2be8b7b1ec80319e023b703a7e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "abcwaas-0.1.7-javadoc.jar",
          "url": "abcwaas-0.1.7-javadoc.jar",
          "size": 383876,
          "sha512": "d31712f1964853f4305d1aeab4a9baa67ace611d53c3f5313c1b848c6b4336f8684fb07e097084cfae654116878c189d7b371a4ff4354910933f5b5e3eebf8cf",
          "sha256": "3e65c915c981393fb8c79f6673a375f70552dce3c78a1b64a307b7898f68d136",
          "sha1": "e08cbcd42b34cd885ecf695e2c2f0b339ad048fd",
          "md5": "d4c2d2b47d38952471bee5ad39829ac7"
        }
      ]
    }
  ]
}
