{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcwaas",
    "version": "0.1.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.ahnlab",
          "module": "abcmpc",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcwaas-0.1.22.aar",
          "url": "abcwaas-0.1.22.aar",
          "size": 9526294,
          "sha512": "a2dcaf6dd2e37ccc6aff8b0b3befa45a6eb91fe925734646344766c036fffd43faab837b0a9ddb9432611da6232280c9dc98d3fc0b6167efd65b1127ce7b7b7c",
          "sha256": "fa448ca6d8450c86010118469f5cfe07ff841f83386edd90e42a598f0417ce58",
          "sha1": "afde3faf44558a5d4d0ab6b535f7114594eb42e9",
          "md5": "37b4d792e564048534ea31d69eaaa408"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ahnlab",
          "module": "abcmpc",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcwaas-0.1.22.aar",
          "url": "abcwaas-0.1.22.aar",
          "size": 9526294,
          "sha512": "a2dcaf6dd2e37ccc6aff8b0b3befa45a6eb91fe925734646344766c036fffd43faab837b0a9ddb9432611da6232280c9dc98d3fc0b6167efd65b1127ce7b7b7c",
          "sha256": "fa448ca6d8450c86010118469f5cfe07ff841f83386edd90e42a598f0417ce58",
          "sha1": "afde3faf44558a5d4d0ab6b535f7114594eb42e9",
          "md5": "37b4d792e564048534ea31d69eaaa408"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "abcwaas-0.1.22-sources.jar",
          "url": "abcwaas-0.1.22-sources.jar",
          "size": 9056,
          "sha512": "d125c283990c19f63be91b447c5f57db9468ec7363cc65cdc185721edd91c674a3e70c34a8cd2bce733edab4643eb7261102cc4189969c178cf3f84b88423169",
          "sha256": "698f06661afa4f44807fcbb5c23a5638b327d9fda007a8e6b92f236bddc56fc1",
          "sha1": "dbc31042120e1e4d7b9d8937443f66a8d9696c6a",
          "md5": "80f5e75eda39cf17c60de68ccb618b70"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "abcwaas-0.1.22-javadoc.jar",
          "url": "abcwaas-0.1.22-javadoc.jar",
          "size": 393509,
          "sha512": "0ef8de737239edd27066a78a48189d94377f1a784fda457bb5b22db4d278cb8333ea55e63459bbf59e384e9fd50edc59687d5599aa92e64f9bee6b12c9f40464",
          "sha256": "aaed4ef205ee90a9cd2f920af4b9bce68cb825ca9bb14d8caba28eaf8c69c6d6",
          "sha1": "14db4884a235e6620b606279ab65ab1a39e8358e",
          "md5": "57cbdfb277953047ca63fbc1d3c5b122"
        }
      ]
    }
  ]
}
