{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ahnlab",
    "module": "abcwaas",
    "version": "0.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.ahnlab",
          "module": "abcmpc",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcwaas-0.1.11.aar",
          "url": "abcwaas-0.1.11.aar",
          "size": 9113773,
          "sha512": "7190d8759f59cbd8dc14966d6872106232b851e5dd491a6f06ffa16278b200a213318e214a4649d9c04380a5704161bce1421078baabe8b5b82a0bd8208f6067",
          "sha256": "64d68d3c2787a8ad18b15b62a0f2aacb970dc0c5e68d4526c6b1b88442d064a8",
          "sha1": "9499a9ab745f045a257fe91d2d1e3301315f7fe6",
          "md5": "ed669db19621abdbc84d6fa41d3526d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ahnlab",
          "module": "abcmpc",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "abcwaas-0.1.11.aar",
          "url": "abcwaas-0.1.11.aar",
          "size": 9113773,
          "sha512": "7190d8759f59cbd8dc14966d6872106232b851e5dd491a6f06ffa16278b200a213318e214a4649d9c04380a5704161bce1421078baabe8b5b82a0bd8208f6067",
          "sha256": "64d68d3c2787a8ad18b15b62a0f2aacb970dc0c5e68d4526c6b1b88442d064a8",
          "sha1": "9499a9ab745f045a257fe91d2d1e3301315f7fe6",
          "md5": "ed669db19621abdbc84d6fa41d3526d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "abcwaas-0.1.11-sources.jar",
          "url": "abcwaas-0.1.11-sources.jar",
          "size": 7480,
          "sha512": "aafd529ad928b72193ccd55766f2118965b89ae16c23cc219cb6f6dad2dcf3c26e2c530f64870f703e00b03d5a44c4036ee39de1901c04150afc38e2c0af2697",
          "sha256": "e3e0588db179889541f3531f3f5144c04f63331aa021329f3a4e81815f3416cc",
          "sha1": "aa07a08d418431e5aa914946980315ba86aa92ba",
          "md5": "8c7eb07b20f63c2b78ebd6543c85d504"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "abcwaas-0.1.11-javadoc.jar",
          "url": "abcwaas-0.1.11-javadoc.jar",
          "size": 380253,
          "sha512": "22240a31e740f41d802a2ad1784dda7077f41385430875020740fba34ee25da6e33e2d1b2aaafd2dc7f955ce87cd1c8c8fac55714d0498e34a564b7e018a1982",
          "sha256": "1e5cb7e44b23c15cfbe4ccd7249eb58d37e5b706c0d6fe381bf507d78f799f68",
          "sha1": "1b7f5af97928a445ac0e9eefb8b71b516c1e62ad",
          "md5": "43984a9f724083ad7b4f0058c9ad3e96"
        }
      ]
    }
  ]
}
